### ISSUE TITLE
Which BOM should we follow?

### ISSUE THREAD

**Issue by Gaetan36** [RickG7191/EnderWire-Open#1]
Good morning,
Firstly, thank you for your incredible work, it perfectly meets what I was looking for.
To avoid making mistakes, could you tell me which BOM I should follow please?
Thank you so much

**Comment by RickG7191** [comment]
At the moment there isn't a BOM developed for this other than what is documented within the Fusion CAD files. I'll see if I can put something together.

**Comment by Gaetan36** [comment]
Alright i understand.
Or maybe i can follow the BOM of https://github.com/walttriano/VoronUsers/tree/master/printer_mods/Triano/Ender_3Pro_Switchwire ?

**Comment by Gaetan36** [comment]
Alright, i will see the CAD files then. Thank for your answer

**Comment by RickG7191** [comment]
I've added [BOM by Component](https://github.com/RickG7191/EnderWire-Open/blob/main/BOM-By-Component.md).
