### ISSUE TITLE
Deck Panel dxf files

### ISSUE THREAD

**Issue by Gaetan36** [RickG7191/EnderWire-Open#2]
Good morning,
Is it possible to have the deck panels in one piece (top and bottom) in dxf file please ?
It seems to me that the upper deck must still have two parts.
I would like to have them laser cut from plexiglass to have a clean surface.
I thank you in advance.

**Comment by RickG7191** [comment]
Added [DXF](https://github.com/RickG7191/EnderWire-Open/tree/main/DXF) files.

**Comment by Gaetan36** [comment]
That's perfect, thank you very much !
